import fs from "node:fs";
import path from "node:path";

/**
 * Refuse to drop schemas in a database that is not ours.
 *
 * WHY THIS EXISTS, and it is not hypothetical. Building the harborbistro suite,
 * a `docker run -p 127.0.0.1:55434:5432` SILENTLY FAILED to bind. The container
 * came up publishing nothing, and that port already belonged to another
 * session's scratch database. The test connected to THEIRS over TCP and was
 * refused only because the password differed. Had the credentials matched,
 * `beforeAll` would have run DROP SCHEMA public CASCADE on someone else's data.
 *
 * Three things made it dangerous rather than obvious:
 *   - `docker exec psql` kept working, because that uses the container's local
 *     socket with trust auth. Every manual query looked perfect; only TCP, the
 *     path the tests use, went somewhere else.
 *   - The error read "password authentication failed", which looks like a typo
 *     in a credential, not like talking to the wrong database.
 *   - The existing guard checked the URL for "prod", "neon" and "portal".
 *     **That is a check for a SMELL, not for an IDENTITY.** "Another
 *     developer's scratch database on localhost" passes it perfectly.
 *
 * So this asks the database what it contains. A database is ours if `public`
 * is empty or holds only tables this schema defines. One unfamiliar table and
 * we stop, naming them. It works regardless of credentials, ports, or how the
 * URL happens to read.
 *
 * THE TABLE LIST IS DERIVED FROM db/schema.sql, never hand-maintained. A
 * hardcoded list is the same failure as the hand-copied DROP list that broke
 * every caller twice when `pristine` and then `ops` were added: it is correct
 * until someone adds a table, and then it is wrong in the direction that
 * refuses valid work.
 */

let cached: Set<string> | undefined;

/** Table names db/schema.sql creates in `public`. */
export function ownTables(schemaPath?: string): Set<string> {
  if (cached && !schemaPath) return cached;
  const file = schemaPath ?? path.join(process.cwd(), "db", "schema.sql");
  const sql = fs.readFileSync(file, "utf8");
  const names = new Set<string>();
  // Bare `CREATE TABLE <name> (` only: a schema-qualified name (pristine.x,
  // ops.x) is not a public table, and the pristine copies are generated by a
  // DO block rather than written out.
  const re = /^\s*CREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS\s+)([a-z_][a-z0-9_]*)\s*\(/gim;
  let m: RegExpExecArray | null;
  while ((m = re.exec(sql)) !== null) names.add(m[1].toLowerCase());
  if (!schemaPath) cached = names;
  return names;
}

type QueryFn = (sql: string) => Promise<{ rows: Array<Record<string, unknown>> }>;

export async function refuseIfNotOurDatabase(
  query: QueryFn,
  schemaPath?: string,
): Promise<void> {
  const mine = ownTables(schemaPath);
  if (mine.size === 0) {
    throw new Error(
      "Could not read any table names out of db/schema.sql, so there is nothing " +
        "to compare against. Refusing to drop anything.",
    );
  }

  const { rows } = await query(
    "SELECT current_database() AS datname, tablename FROM pg_tables WHERE schemaname = 'public'",
  );
  const foreign = rows
    .map((r) => String(r.tablename))
    .filter((t) => !mine.has(t.toLowerCase()))
    .sort();

  if (foreign.length) {
    const db = rows.length ? String(rows[0].datname) : "(unknown)";
    throw new Error(
      `REFUSING to drop schemas in database "${db}": its public schema holds ` +
        `tables this project does not define -- ${foreign.join(", ")}. That is ` +
        "somebody else's database. Check DATABASE_URL and the port: a docker " +
        "port binding that fails silently is enough to point you at another " +
        "session's Postgres, and the URL will look perfectly innocent.",
    );
  }
}
